---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "openstad.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openstad.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "openstad.frontend.fullname" . }}-deployment
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.label }}
    spec:
      containers:
        - name: {{ template "openstad.frontend.fullname" . }}
          image: {{ .Values.frontend.deploymentContainer.image }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.httpPort }}
              protocol: TCP
          env:
            - name: DEFAULT_HOST
              value: {{ .Values.host.www }}
            - name: APP_URL
              value: {{ .Values.host.https }}
            - name: API
              value: https://{{ index .Values.api.ingress.hosts 0 }}
            - name: IMAGE_API_URL
              value: https://{{ index .Values.image.ingress.hosts 0 }}
            - name: IMAGE_API_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: fixed_token
                  name: openstad-auth-credentials
            - name: HOST_DOMAIN
              valueFrom:
                secretKeyRef:
                  key: frontend
                  name: openstad-hosts
            - name: PORT
              value: {{ .Values.frontend.service.httpPort | quote }}
            - name: SITE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: fixed_token
                  name: openstad-auth-credentials
            - name: MONGO_DB_HOST
              valueFrom:
                secretKeyRef:
                  key: hostname
                  name: openstad-mongo-credentials
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: hostname
                  name: openstad-mongo-credentials
            - name: DEFAULT_DB
              valueFrom:
                secretKeyRef:
                  key: database
                  name: openstad-mongo-credentials
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          resources:
{{ toYaml .Values.frontend.resources | indent 12 }}
          volumeMounts:
            - mountPath: /home/app/data
              name: data-vol
            - mountPath: /home/app/public/uploads
              name: data-uploads
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      volumes:
        - name: data-vol
          persistentVolumeClaim:
            claimName: frontend-data-claim
        - name: data-uploads
          persistentVolumeClaim:
            claimName: frontend-uploads-claim
